services:
  zookeeper-1-372:
    image: imdhruv99/zookeeper:3.8.3
    container_name: zookeeper-1-372
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-372:2888:3888,zookeeper-2-372:2888:3888,zookeeper-3-372:2888:3888
    ports:
      - "12181:2181"
    volumes:
      - zookeeper_data1_372:/opt/zookeeper/data
    networks:
      - kafka_network_372
    restart: always

  zookeeper-2-372:
    image: imdhruv99/zookeeper:3.8.3
    container_name: zookeeper-2-372
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-372:2888:3888,zookeeper-2-372:2888:3888,zookeeper-3-372:2888:3888
    ports:
      - "12182:2181"
    volumes:
      - zookeeper_data2_372:/opt/zookeeper/data
    networks:
      - kafka_network_372
    restart: always

  zookeeper-3-372:
    image: imdhruv99/zookeeper:3.8.3
    container_name: zookeeper-3-372
    environment:
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-372:2888:3888,zookeeper-2-372:2888:3888,zookeeper-3-372:2888:3888
    ports:
      - "12183:2181"
    volumes:
      - zookeeper_data3_372:/opt/zookeeper/data
    networks:
      - kafka_network_372
    restart: always

  kafka-1-372:
    image: imdhruv99/kafka:3.7.2
    container_name: kafka-1-372
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19091,EXTERNAL://0.0.0.0:19092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1-372:19091,EXTERNAL://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-372:2181,zookeeper-2-372:2181,zookeeper-3-372:2181
    ports:
      - "19091:19091"
      - "19092:19092"
    volumes:
      - kafka_data1_372:/var/lib/kafka
    networks:
      - kafka_network_372
    depends_on:
      - zookeeper-1-372
      - zookeeper-2-372
      - zookeeper-3-372
    restart: always

  kafka-2-372:
    image: imdhruv99/kafka:3.7.2
    container_name: kafka-2-372
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19093,EXTERNAL://0.0.0.0:19094
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2-372:19093,EXTERNAL://localhost:19094
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-372:2181,zookeeper-2-372:2181,zookeeper-3-372:2181
    ports:
      - "19093:19093"
      - "19094:19094"
    volumes:
      - kafka_data2_372:/var/lib/kafka
    networks:
      - kafka_network_372
    depends_on:
      - zookeeper-1-372
      - zookeeper-2-372
      - zookeeper-3-372
    restart: always

  kafka-3-372:
    image: imdhruv99/kafka:3.7.2
    container_name: kafka-3-372
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:19095,EXTERNAL://0.0.0.0:19096
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3-372:19095,EXTERNAL://localhost:19096
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-372:2181,zookeeper-2-372:2181,zookeeper-3-372:2181
    ports:
      - "19095:19095"
      - "19096:19096"
    volumes:
      - kafka_data3_372:/var/lib/kafka
    networks:
      - kafka_network_372
    depends_on:
      - zookeeper-1-372
      - zookeeper-2-372
      - zookeeper-3-372
    restart: always

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "18080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Kafka-3.7.2
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1-372:19091,kafka-2-372:19093,kafka-3-372:19095
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper-1-372:2181,zookeeper-2-372:2181,zookeeper-3-372:2181
    networks:
      - kafka_network_372
    depends_on:
      - kafka-1-372
      - kafka-2-372
      - kafka-3-372

networks:
  kafka_network_372:
    driver: bridge

volumes:
  zookeeper_data1_372:
  zookeeper_data2_372:
  zookeeper_data3_372:
  kafka_data1_372:
  kafka_data2_372:
  kafka_data3_372:
