services:
  zookeeper-1-211:
    image: imdhruv99/zookeeper:3.6.1
    container_name: zookeeper-1-211
    environment:
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-211:2888:3888,zookeeper-2-211:2888:3888,zookeeper-3-211:2888:3888
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data1_211:/opt/zookeeper/data
    networks:
      - kafka_network_211
    restart: always

  zookeeper-2-211:
    image: imdhruv99/zookeeper:3.6.1
    container_name: zookeeper-2-211
    environment:
      - ZOOKEEPER_SERVER_ID=2
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-211:2888:3888,zookeeper-2-211:2888:3888,zookeeper-3-211:2888:3888
    ports:
      - "2182:2181"
    volumes:
      - zookeeper_data2_211:/opt/zookeeper/data
    networks:
      - kafka_network_211
    restart: always

  zookeeper-3-211:
    image: imdhruv99/zookeeper:3.6.1
    container_name: zookeeper-3-211
    environment:
      - ZOOKEEPER_SERVER_ID=3
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_INIT_LIMIT=5
      - ZOOKEEPER_SYNC_LIMIT=2
      - ZOOKEEPER_SERVERS=zookeeper-1-211:2888:3888,zookeeper-2-211:2888:3888,zookeeper-3-211:2888:3888
    ports:
      - "2183:2181"
    volumes:
      - zookeeper_data3_211:/opt/zookeeper/data
    networks:
      - kafka_network_211
    restart: always

  kafka-1-211:
    image: imdhruv99/kafka:2.1.1
    container_name: kafka-1-211
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29091,EXTERNAL://0.0.0.0:9091
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1-211:29091,EXTERNAL://localhost:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-211:2181,zookeeper-2-211:2181,zookeeper-3-211:2181
    ports:
      - "9091:9091"
      - "29091:29091"
    volumes:
      - kafka_data1_211:/var/lib/kafka
    networks:
      - kafka_network_211
    depends_on:
      - zookeeper-1-211
      - zookeeper-2-211
      - zookeeper-3-211
    restart: always

  kafka-2-211:
    image: imdhruv99/kafka:2.1.1
    container_name: kafka-2-211
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2-211:29092,EXTERNAL://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-211:2181,zookeeper-2-211:2181,zookeeper-3-211:2181
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafka_data2_211:/var/lib/kafka
    networks:
      - kafka_network_211
    depends_on:
      - zookeeper-1-211
      - zookeeper-2-211
      - zookeeper-3-211
    restart: always

  kafka-3-211:
    image: imdhruv99/kafka:2.1.1
    container_name: kafka-3-211
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:29093,EXTERNAL://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-3-211:29093,EXTERNAL://localhost:9093
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper-1-211:2181,zookeeper-2-211:2181,zookeeper-3-211:2181
    ports:
      - "9093:9093"
      - "29093:29093"
    volumes:
      - kafka_data3_211:/var/lib/kafka
    networks:
      - kafka_network_211
    depends_on:
      - zookeeper-1-211
      - zookeeper-2-211
      - zookeeper-3-211
    restart: always

networks:
  kafka_network_211:
    driver: bridge

volumes:
  zookeeper_data1_211:
  zookeeper_data2_211:
  zookeeper_data3_211:
  kafka_data1_211:
  kafka_data2_211:
  kafka_data3_211:
