services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=Kafka-2.1.1
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1-211:29091,kafka-2-211:29092,kafka-3-211:29093
      - KAFKA_CLUSTERS_1_NAME=Kafka-3.7.2
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=kafka-1-372:19091,kafka-2-372:19093,kafka-3-372:19095
    networks:
      - kafka_211_kafka_network_211
      - kafka_372_kafka_network_372

networks:
  kafka_211_kafka_network_211:
    external: true
  kafka_372_kafka_network_372:
    external: true
